### ISSUE TITLE
Player Model

### ISSUE THREAD

**Issue by erik-stodola** [comp371samurais/samurai-dash#1]

**Comment by erik-stodola** [comment]
Attempt to create a model from basic primitives, if that does not work just import a model. Good luck!

**Comment by kyle-ilantzis** [comment]
The sheep should have a particle emitter from the behind, color brown, ... shit!!!

**Comment by kyle-ilantzis** [comment]
The sheep needs a capsule fitted to him

**Comment by erik-stodola** [comment]
Not trying to rain on your poop parade ;) Though in the models there are actually no normal to obtain, so I cannot retrieve anything. Also in regards to the capsule I think it would be safer to collaborate with you on that, because I am bit confused of how to integrate the capsule on my sheep. See you tommorow

**Comment by erik-stodola** [comment]
Character present with capsule and able to move. (Kyle support)
