### ISSUE TITLE
Spline (The Track)

### ISSUE THREAD

**Issue by erik-stodola** [comp371samurais/samurai-dash#2]
Create some sort of circular like track, so the model can ride along it. Good luck!

**Comment by kyle-ilantzis** [comment]
The first rough draft is here a1d3dac387d6982e6a607162fa6e9d2b9db1dc88

You can create a spline with desired control points.

Next steps:

Function SplineModel.at(time) gives a position on the track after time,
position should be the center of the track.
(this means moving the formula from SplineFacotry::makeTriangleStrip to the SplineModel class)

Make the spline creation make edges trackWidth/2 distance from the center of the the spline.

Finally, try some way to make the track circular

**Comment by kyle-ilantzis** [comment]
Now the spline is satisfactory

it goes from z=0 to z= - infinity and has a constants width of x = -width/2 to x = width/2

The y value of the spline varies smoothly.

**Comment by erik-stodola** [comment]
Great job Kyle, I will be closing this issue.
